apiVersion: v1
kind: Service
metadata:
  labels:
    livestock: backend
  name: backend-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    livestock: backend
  type: ClusterIP
