apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    livestock: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      livestock: frontend
  template:
    metadata:
      labels:
        livestock: backend
    spec:
      serviceAccountName: eks-sa
      containers:
      - image: kyungpyoryu/live-stock:1b4895ba369de48f3250a0662b9351534cd15da4
        name: live-stock

