apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: redis
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 
  hostPath:
    path: "/mnt/data"  # 워커 노드의 로컬 경로
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-node
              operator: In
              values:
                - "true"  # storage-node=true 라벨이 있는 노드에만 바인딩
