apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rds-secret-provider
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: rds-secret
      type: Opaque
      data:
        - objectName: spring.datasource.username
          key: spring.datasource.username
        - objectName: spring.datasource.password
          key: spring.datasource.password
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-northeast-1:396913715402:secret:prod/livestock/rds/ryu-3nn1TW"
        jmesPath:
          - path: username
            objectAlias: spring.datasource.username
          - path: password
            objectAlias: spring.datasource.password

