apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/redis

patchesStrategicMerge:
  - redis-patch.yaml

#patchesJson6902:
#- target:
#    version: apps/v1
#    kind: StatefulSet
#    name: my-redis-node
#  path: redis-pvc-patch.json

