apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-redis-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kpryu6/livestock'
    targetRevision: main
    path: k8s/overlays/prod/redis
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kpryu6/livestock'
    targetRevision: main
    path: k8s/overlays/prod/frontend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

