- name: Uninstall AWS Load Balancer Controller and associated resources
  hosts: localhost
  gather_facts: false
  vars:
    aws_account_id: "396913715402"
    eks_cluster_name: "eks-ryu"
    aws_region: "ap-northeast-1"
  tasks:
    - name: Retrieve EKS Cluster VPC ID
      ansible.builtin.command: >
        aws eks describe-cluster --name {{ eks_cluster_name }} --region {{ aws_region }} --query "cluster.resourcesVpcConfig.vpcId" --output text
      register: eks_vpc_cmd
      changed_when: false

    - name: Set eks_vpc_id fact
      set_fact:
        eks_vpc_id: "{{ eks_vpc_cmd.stdout }}"

    - name: Retrieve EKS OIDC provider
      ansible.builtin.command: >
        aws eks describe-cluster --name {{ eks_cluster_name }} --region {{ aws_region }} --query "cluster.identity.oidc.issuer" --output text
      register: eks_oidc_cmd
      changed_when: false

    - name: Set eks_oidc_provider fact
      set_fact:
        eks_oidc_provider: "{{ eks_oidc_cmd.stdout | regex_replace('^https://', '') }}"

    - name: Uninstall AWS Load Balancer Controller via Helm
      ansible.builtin.shell: >
        helm uninstall aws-load-balancer-controller -n kube-system
      environment:
        HELM_EXPERIMENTAL_OCI: "1"

    - name: Delete Service Account for AWS Load Balancer Controller
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: aws-load-balancer-controller
            namespace: kube-system

    - name: Delete IAM role for AWS Load Balancer Controller
      amazon.aws.iam_role:
        name: "AWSLoadBalancerControllerIAMRole"
        state: absent

    - name: Delete IAM policy for AWS Load Balancer Controller
      amazon.aws.iam_policy:
        iam_type: "role"
        iam_name: "AWSLoadBalancerControllerIAMRole"
        policy_name: "AWSLoadBalancerControllerIAMPolicy"
        state: absent

