- name: Install Secrets Store CSI Driver and AWS Secrets Provider
  hosts: localhost
  tasks:
    - name: Add Helm repository for Secrets Store CSI Driver
      command: helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts

    - name: Add Helm repository for AWS Secrets Provider
      command: helm repo add aws-secrets-manager https://aws.github.io/secrets-store-csi-driver-provider-aws

    - name: Update Helm repositories
      command: helm repo update

    - name: Install or Upgrade Secrets Store CSI Driver with Secret Sync enabled
      command: >
        helm upgrade --install -n kube-system csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --set secrets-store-csi-driver.syncSecret.enabled=true 

    - name: Install or Upgrade AWS Secrets Provider
      command: >
        helm upgrade --install -n kube-system secrets-provider-aws aws-secrets-manager/secrets-store-csi-driver-provider-aws
    
    - name: Apply RBAC for Secrets Store CSI Driver
      kubernetes.core.k8s:
        state: present
        src: ./rbac_secrets_store.yaml

