apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: secrets-provider-aws
    meta.helm.sh/release-namespace: kube-system
  labels:
    app: secrets-store-csi-driver-provider-aws
    app.kubernetes.io/instance: secrets-provider-aws
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver-provider-aws
    helm.sh/chart: secrets-store-csi-driver-provider-aws-0.3.11
  name: secrets-provider-aws-secrets-store-csi-driver-provider-aws-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get

# 시크릿 생성해야해서 추가   
- apiGroups: [""]
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete
- apiGroups:
    - secrets-store.csi.x-k8s.io
  resources:
    - secretproviderclasses
    - secretproviderclasspodstatuses
  verbs:
    - get
    - list
    - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: secrets-provider-aws
    meta.helm.sh/release-namespace: kube-system
  labels:
    app: secrets-store-csi-driver-provider-aws
    app.kubernetes.io/instance: secrets-provider-aws
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-store-csi-driver-provider-aws
    helm.sh/chart: secrets-store-csi-driver-provider-aws-0.3.11
  name: secrets-provider-aws-secrets-store-csi-driver-provider-aws-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-provider-aws-secrets-store-csi-driver-provider-aws-cluster-role
subjects:
- kind: ServiceAccount
  name: secrets-provider-aws-secrets-store-csi-driver-provider-aws
  namespace: kube-system
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: kube-system
