apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend

# 초기 상태에서 images 블록을 정의
# kustomize edit set image 명령으로 CI에서 수정
images:
- name: kyungpyoryu/live-stock
  newName: kyungpyoryu/live-stock
  newTag: c69f1c0cf151eefae2e57cf8bc826211ea5c9837
